/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoProductionCompanyRouteImport } from './routes/video-production-company'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioRentalRouteImport } from './routes/studio-rental'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MusicVideoProductionServicesRouteImport } from './routes/music-video-production-services'
import { Route as MotionGraphicsRouteImport } from './routes/motion-graphics'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ExplainerVideoProductionRouteImport } from './routes/explainer-video-production'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as DocumentaryFilmMakerRouteImport } from './routes/documentary-film-maker'
import { Route as CorporateFilmsRouteImport } from './routes/corporate-films'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandVideoProductionServicesRouteImport } from './routes/brand-video-production-services'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AnimationVideosRouteImport } from './routes/animation-videos'
import { Route as AdFilmsMakerRouteImport } from './routes/ad-films-maker'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicVideoSlotsRouteImport } from './routes/api/public/video-slots'
import { Route as ApiPublicSubmitFormRouteImport } from './routes/api/public/submit-form'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin.videos'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/_authenticated/admin.submissions'
import { Route as AuthenticatedAdminBlogsRouteImport } from './routes/_authenticated/admin.blogs'

const VideoProductionCompanyRoute = VideoProductionCompanyRouteImport.update({
  id: '/video-production-company',
  path: '/video-production-company',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRentalRoute = StudioRentalRouteImport.update({
  id: '/studio-rental',
  path: '/studio-rental',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicVideoProductionServicesRoute =
  MusicVideoProductionServicesRouteImport.update({
    id: '/music-video-production-services',
    path: '/music-video-production-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const MotionGraphicsRoute = MotionGraphicsRouteImport.update({
  id: '/motion-graphics',
  path: '/motion-graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainerVideoProductionRoute =
  ExplainerVideoProductionRouteImport.update({
    id: '/explainer-video-production',
    path: '/explainer-video-production',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentaryFilmMakerRoute = DocumentaryFilmMakerRouteImport.update({
  id: '/documentary-film-maker',
  path: '/documentary-film-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateFilmsRoute = CorporateFilmsRouteImport.update({
  id: '/corporate-films',
  path: '/corporate-films',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandVideoProductionServicesRoute =
  BrandVideoProductionServicesRouteImport.update({
    id: '/brand-video-production-services',
    path: '/brand-video-production-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationVideosRoute = AnimationVideosRouteImport.update({
  id: '/animation-videos',
  path: '/animation-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdFilmsMakerRoute = AdFilmsMakerRouteImport.update({
  id: '/ad-films-maker',
  path: '/ad-films-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicVideoSlotsRoute = ApiPublicVideoSlotsRouteImport.update({
  id: '/api/public/video-slots',
  path: '/api/public/video-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmitFormRoute = ApiPublicSubmitFormRouteImport.update({
  id: '/api/public/submit-form',
  path: '/api/public/submit-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/admin/videos',
    path: '/admin/videos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/admin/submissions',
    path: '/admin/submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBlogsRoute = AuthenticatedAdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ad-films-maker': typeof AdFilmsMakerRoute
  '/animation-videos': typeof AnimationVideosRoute
  '/blog': typeof BlogRouteWithChildren
  '/brand-video-production-services': typeof BrandVideoProductionServicesRoute
  '/contact': typeof ContactRoute
  '/corporate-films': typeof CorporateFilmsRoute
  '/documentary-film-maker': typeof DocumentaryFilmMakerRoute
  '/enquiry': typeof EnquiryRoute
  '/explainer-video-production': typeof ExplainerVideoProductionRoute
  '/mcp': typeof McpRoute
  '/motion-graphics': typeof MotionGraphicsRoute
  '/music-video-production-services': typeof MusicVideoProductionServicesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-rental': typeof StudioRentalRoute
  '/terms': typeof TermsRoute
  '/video-production-company': typeof VideoProductionCompanyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/blogs': typeof AuthenticatedAdminBlogsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/api/public/submit-form': typeof ApiPublicSubmitFormRoute
  '/api/public/video-slots': typeof ApiPublicVideoSlotsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ad-films-maker': typeof AdFilmsMakerRoute
  '/animation-videos': typeof AnimationVideosRoute
  '/blog': typeof BlogRouteWithChildren
  '/brand-video-production-services': typeof BrandVideoProductionServicesRoute
  '/contact': typeof ContactRoute
  '/corporate-films': typeof CorporateFilmsRoute
  '/documentary-film-maker': typeof DocumentaryFilmMakerRoute
  '/enquiry': typeof EnquiryRoute
  '/explainer-video-production': typeof ExplainerVideoProductionRoute
  '/mcp': typeof McpRoute
  '/motion-graphics': typeof MotionGraphicsRoute
  '/music-video-production-services': typeof MusicVideoProductionServicesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-rental': typeof StudioRentalRoute
  '/terms': typeof TermsRoute
  '/video-production-company': typeof VideoProductionCompanyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/blogs': typeof AuthenticatedAdminBlogsRoute
  '/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/api/public/submit-form': typeof ApiPublicSubmitFormRoute
  '/api/public/video-slots': typeof ApiPublicVideoSlotsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ad-films-maker': typeof AdFilmsMakerRoute
  '/animation-videos': typeof AnimationVideosRoute
  '/blog': typeof BlogRouteWithChildren
  '/brand-video-production-services': typeof BrandVideoProductionServicesRoute
  '/contact': typeof ContactRoute
  '/corporate-films': typeof CorporateFilmsRoute
  '/documentary-film-maker': typeof DocumentaryFilmMakerRoute
  '/enquiry': typeof EnquiryRoute
  '/explainer-video-production': typeof ExplainerVideoProductionRoute
  '/mcp': typeof McpRoute
  '/motion-graphics': typeof MotionGraphicsRoute
  '/music-video-production-services': typeof MusicVideoProductionServicesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-rental': typeof StudioRentalRoute
  '/terms': typeof TermsRoute
  '/video-production-company': typeof VideoProductionCompanyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/_authenticated/admin/blogs': typeof AuthenticatedAdminBlogsRoute
  '/_authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/api/public/submit-form': typeof ApiPublicSubmitFormRoute
  '/api/public/video-slots': typeof ApiPublicVideoSlotsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ad-films-maker'
    | '/animation-videos'
    | '/blog'
    | '/brand-video-production-services'
    | '/contact'
    | '/corporate-films'
    | '/documentary-film-maker'
    | '/enquiry'
    | '/explainer-video-production'
    | '/mcp'
    | '/motion-graphics'
    | '/music-video-production-services'
    | '/privacy'
    | '/sitemap.xml'
    | '/studio-rental'
    | '/terms'
    | '/video-production-company'
    | '/blog/$slug'
    | '/admin/blogs'
    | '/admin/submissions'
    | '/admin/videos'
    | '/api/public/submit-form'
    | '/api/public/video-slots'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ad-films-maker'
    | '/animation-videos'
    | '/blog'
    | '/brand-video-production-services'
    | '/contact'
    | '/corporate-films'
    | '/documentary-film-maker'
    | '/enquiry'
    | '/explainer-video-production'
    | '/mcp'
    | '/motion-graphics'
    | '/music-video-production-services'
    | '/privacy'
    | '/sitemap.xml'
    | '/studio-rental'
    | '/terms'
    | '/video-production-company'
    | '/blog/$slug'
    | '/admin/blogs'
    | '/admin/submissions'
    | '/admin/videos'
    | '/api/public/submit-form'
    | '/api/public/video-slots'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ad-films-maker'
    | '/animation-videos'
    | '/blog'
    | '/brand-video-production-services'
    | '/contact'
    | '/corporate-films'
    | '/documentary-film-maker'
    | '/enquiry'
    | '/explainer-video-production'
    | '/mcp'
    | '/motion-graphics'
    | '/music-video-production-services'
    | '/privacy'
    | '/sitemap.xml'
    | '/studio-rental'
    | '/terms'
    | '/video-production-company'
    | '/blog/$slug'
    | '/_authenticated/admin/blogs'
    | '/_authenticated/admin/submissions'
    | '/_authenticated/admin/videos'
    | '/api/public/submit-form'
    | '/api/public/video-slots'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdFilmsMakerRoute: typeof AdFilmsMakerRoute
  AnimationVideosRoute: typeof AnimationVideosRoute
  BlogRoute: typeof BlogRouteWithChildren
  BrandVideoProductionServicesRoute: typeof BrandVideoProductionServicesRoute
  ContactRoute: typeof ContactRoute
  CorporateFilmsRoute: typeof CorporateFilmsRoute
  DocumentaryFilmMakerRoute: typeof DocumentaryFilmMakerRoute
  EnquiryRoute: typeof EnquiryRoute
  ExplainerVideoProductionRoute: typeof ExplainerVideoProductionRoute
  McpRoute: typeof McpRoute
  MotionGraphicsRoute: typeof MotionGraphicsRoute
  MusicVideoProductionServicesRoute: typeof MusicVideoProductionServicesRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRentalRoute: typeof StudioRentalRoute
  TermsRoute: typeof TermsRoute
  VideoProductionCompanyRoute: typeof VideoProductionCompanyRoute
  ApiPublicSubmitFormRoute: typeof ApiPublicSubmitFormRoute
  ApiPublicVideoSlotsRoute: typeof ApiPublicVideoSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-production-company': {
      id: '/video-production-company'
      path: '/video-production-company'
      fullPath: '/video-production-company'
      preLoaderRoute: typeof VideoProductionCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-rental': {
      id: '/studio-rental'
      path: '/studio-rental'
      fullPath: '/studio-rental'
      preLoaderRoute: typeof StudioRentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-video-production-services': {
      id: '/music-video-production-services'
      path: '/music-video-production-services'
      fullPath: '/music-video-production-services'
      preLoaderRoute: typeof MusicVideoProductionServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion-graphics': {
      id: '/motion-graphics'
      path: '/motion-graphics'
      fullPath: '/motion-graphics'
      preLoaderRoute: typeof MotionGraphicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainer-video-production': {
      id: '/explainer-video-production'
      path: '/explainer-video-production'
      fullPath: '/explainer-video-production'
      preLoaderRoute: typeof ExplainerVideoProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentary-film-maker': {
      id: '/documentary-film-maker'
      path: '/documentary-film-maker'
      fullPath: '/documentary-film-maker'
      preLoaderRoute: typeof DocumentaryFilmMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-films': {
      id: '/corporate-films'
      path: '/corporate-films'
      fullPath: '/corporate-films'
      preLoaderRoute: typeof CorporateFilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-video-production-services': {
      id: '/brand-video-production-services'
      path: '/brand-video-production-services'
      fullPath: '/brand-video-production-services'
      preLoaderRoute: typeof BrandVideoProductionServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animation-videos': {
      id: '/animation-videos'
      path: '/animation-videos'
      fullPath: '/animation-videos'
      preLoaderRoute: typeof AnimationVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-films-maker': {
      id: '/ad-films-maker'
      path: '/ad-films-maker'
      fullPath: '/ad-films-maker'
      preLoaderRoute: typeof AdFilmsMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/video-slots': {
      id: '/api/public/video-slots'
      path: '/api/public/video-slots'
      fullPath: '/api/public/video-slots'
      preLoaderRoute: typeof ApiPublicVideoSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-form': {
      id: '/api/public/submit-form'
      path: '/api/public/submit-form'
      fullPath: '/api/public/submit-form'
      preLoaderRoute: typeof ApiPublicSubmitFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/submissions': {
      id: '/_authenticated/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/blogs': {
      id: '/_authenticated/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AuthenticatedAdminBlogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminBlogsRoute: typeof AuthenticatedAdminBlogsRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminBlogsRoute: AuthenticatedAdminBlogsRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdFilmsMakerRoute: AdFilmsMakerRoute,
  AnimationVideosRoute: AnimationVideosRoute,
  BlogRoute: BlogRouteWithChildren,
  BrandVideoProductionServicesRoute: BrandVideoProductionServicesRoute,
  ContactRoute: ContactRoute,
  CorporateFilmsRoute: CorporateFilmsRoute,
  DocumentaryFilmMakerRoute: DocumentaryFilmMakerRoute,
  EnquiryRoute: EnquiryRoute,
  ExplainerVideoProductionRoute: ExplainerVideoProductionRoute,
  McpRoute: McpRoute,
  MotionGraphicsRoute: MotionGraphicsRoute,
  MusicVideoProductionServicesRoute: MusicVideoProductionServicesRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRentalRoute: StudioRentalRoute,
  TermsRoute: TermsRoute,
  VideoProductionCompanyRoute: VideoProductionCompanyRoute,
  ApiPublicSubmitFormRoute: ApiPublicSubmitFormRoute,
  ApiPublicVideoSlotsRoute: ApiPublicVideoSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
